CREATE VIEW `Registrasies2015` AS SELECT `r`.`id` AS `registrasie_id`,
         `besoeker_id`,
         `naam`,
         `van`,
         `volleNaam`,
         `epos`,
         `telefoon`,
         `selfoon`,
         `kantoorfoon`,
         `huisfoon`,
         `anderfoon`,
         `geboorteDatum`,
         `geslag_id`,
         `nuusbrief`,
         `unsubscribed`,
         `opmerkings`,
         `b`.`geskep_op` AS `bes_geskep_op`,
         `b`.`geskep_deur` AS `bes_geskep_deur`,
         `b`.`verander_deur` AS `bes_verander_deur`,
         `b`.`verander_op` AS `bes_verander_op`,
        `ekspo_id`,
         `registrasietiepe_id`,
         `vorigebesoek`,
         `hetopgedaag`,
         `wasbyseminaar`,
         `kinders`,
         `kwalifikasie_id`,
         `inkomsteband_id`,
         `instansietiepe_id`,
         `onderwys_id`,
         `posisie_id`,
         `bs_energie`,
         `bs_nuweteg`,
         `bs_konstr`,
         `bs_opvoed`,
         `bs_entrep`,
         `bs_veilig`,
         `bs_voedsel`,
         `bs_buite`,
         `bs_finans`,
         `bs_fees`,
         `oh_gladnie`,
         `oh_geeneskom`,
         `oh_sonpanele`,
         `oh_songeiser`,
         `oh_ledligte`,
         `oh_biogas`,
         `oh_altboumat`,
         `beplaninvesteer_id`,
         `waargehoor_id`,
         `solidariteitlid`,
         `solidariteitkontak`,
         `vw_naam1`,
         `vw_van1`,
         `vw_epos1`,
         `vw_naam2`,
         `vw_van2`,
         `vw_epos2`,
         `vw_naam3`,
         `vw_van3`,
         `vw_epos3`,
         `vw_naam4`,
         `vw_van4`,
         `vw_epos4`,
         `vw_naam5`,
         `vw_van5`,
         `vw_epos5`,
         `gratisrede`,
         `r`.`geskep_op` AS `registrasiedatum`,
         `r`.`geskep_deur` AS `reg_geskep_deur`,
         `r`.`verander_op` AS `reg_verander_op`,
         `r`.`verander_deur` AS `reg_verander_deur`
FROM `tblregistrasies` `r`
LEFT JOIN `tblbesoekers` `b`
    ON `r`.`besoeker_id` = `b`.`id`
WHERE `r`.`ekspo_id` = 5
